In [ ]:
#IN THIS NOTEBOOK WE WILL THROUGH THROUGH SIMPLE REGRESSION MODEL 

In [3]:
!pip install scikit-learn

  Obtaining dependency information for numpy>=1.17.3 from https://files.pythonhosted.org/packages/1a/2e/151484f49fd03944c4a3ad9c418ed193cfd02724e138ac8a9505d056c582/numpy-1.26.4-cp311-cp311-macosx_11_0_arm64.whl.metadata
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.8/114.8 kB 477.5 kB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.0/14.0 MB 628.2 kB/s eta 0:00:0000:0100:01
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tables 3.8.0 requires blosc2~=2.0.0, which is not installed.
tables 3.8.0 requires cython>=0.29.21, which is not installed.
gensim 4.3.0 requires FuzzyTM>=0.4.0, which is not installed.
numba 0.57.1 requires numpy<1.25,>=1.21, but you have numpy 1.26.4 which is incompatibl

In [4]:
import pandas as pd

/Users/harshjavia/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [6]:
df = pd.read_csv("home_prices.csv")
df.head() #loading the dataset

area_sqr_ft  price_lakhs
0          656         39.0
1         1260         83.2
2         1057         86.6
3         1259         59.0
4         1800        140.0

In [8]:
from sklearn.linear_model import LinearRegression  #importing the linearRegression model
model = LinearRegression() #storing our model into object 
model.fit(df[["area_sqr_ft"]], df[["price_lakhs"]]) #.fit is used to train the model and we have to give parameter
#remember that we need to give the paarmeters in 2D ..[[]]

LinearRegression()

In [12]:
model.predict([[1500],[2000]]) #after training we can predict any values given 

/Users/harshjavia/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[ 95.56913434],
       [121.41001208]])

In [13]:
model.coef_ #slope of the data

array([[0.05168176]])

In [14]:
model.intercept_ #intercept of the data

array([18.0465011])

In [15]:
#NOW PRICE = SLOPE * AREA + INTERCEPT 
# slope = 0.051 and intercept = 18.04
# to calculate price of home having area of 1500 sqr ft 
0.051 * 1500 + 18.04 # see we got the nearest value what we got by our model that predicted the price

94.53999999999999