In [ ]:
#IN THIS NOTEBOOK WE WILL GO THROUGH OPERATIONS IN NUMPY 

In [1]:
import numpy as np

In [2]:
rev_q1 = np.array([10,12,7])
rev_q1.ndim  #.ndim function gives us the dimension of the array here its is 1D array

1

In [4]:
rev = np.array([[10,3,6], [5,7,8]])
rev.ndim    #.ndim function gives us the dimension of the array here its is 2D array

2

In [5]:
rev

array([[10,  3,  6],
       [ 5,  7,  8]])

In [9]:
rev[1,0] #gives us the element on that specific location 

np.int64(5)

In [12]:
rev[1,0] = 14 # we can change the element by giving the position 
rev 

array([[10,  3,  6],
       [14,  7,  8]])

In [14]:
rev.size #tells us how many elements are there 

6

In [15]:
rev.itemsize #tells us the bites that elements have 

8

In [16]:
rev.nbytes #tells us the number of bytes 

48

In [17]:
rev.shape #tells us the shape of array

(2, 3)

In [18]:
np.sort(rev) #it sorts the array in ascending order 

array([[ 3,  6, 10],
       [ 7,  8, 14]])

In [20]:
np.sort(rev , axis=None) #it sorts the array in linear form not in the array form 

array([ 3,  6,  7,  8, 10, 14])

In [22]:
np.zeros((5,5)) #prints all zeros in 5,5

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.arange(20,30,2) #it prints the elements between 20 and 30 with the gap of 2 or we can say even numbers

array([20, 22, 24, 26, 28])

In [24]:
np.linspace(10,20,3) #it prints the number between 10 and 20 with equal spacing 

array([10., 15., 20.])

In [25]:
rev.flatten() #it flattens the array in one line

array([10,  3,  6, 14,  7,  8])

In [26]:
rev.reshape(3,2) #it rehshapes the array like first it was 2row and 3column now it is 3row and 2column 

array([[10,  3],
       [ 6, 14],
       [ 7,  8]])

In [27]:
rev.min() #gives minimum element

np.int64(3)

In [28]:
rev.max() #gives maximum element

np.int64(14)

In [29]:
rev.sum() #gives sum of array 

np.int64(48)

In [36]:
for row in rev:
 print("row -> ", row )  #it prints the row 

row ->  [10  3  6]
row ->  [14  7  8]


In [37]:
b = np.array([1,4,16])
b

array([ 1,  4, 16])

In [38]:
np.sqrt(b) #gives squareroot of the array 

array([1., 2., 4.])