In [ ]:
#IN THIS NOTEBOOK WE WILL GO THROUGH BASICS OF NUMPY AND ITS ADVATNAGES 

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np 

In [4]:
arr = np.array([1,2,3])
arr    #numpy representation 

array([1, 2, 3])

In [5]:
l = [1,2,3]
l  #list representation 

[1, 2, 3]

In [6]:
#FOLLOWING ARE THE BENIFITS OF USING NUMPY INSTEAD OF LISTS 

# NUMPY OCCUPIES LESS MEMORY THAN LISTS


In [8]:
python_list = list(range(100))
python_list[:5]

[0, 1, 2, 3, 4]

In [9]:
import sys
sys.getsizeof(python_list[0]) #it tells us the size of one element 

28

In [10]:
import sys
sys.getsizeof(python_list[0])*len(python_list) #it tells us the size of whole list 

2800

In [11]:
np.array = np.arange(100)
np.array[:5]

array([0, 1, 2, 3, 4])

In [13]:
np.array.nbytes

800

In [14]:
# we can clearly see that numpy occupies 800 bytes for 100 elements and lists occupies 2800 bytes
#in lists memories is fragmented and in numpy memories are contigenous 

# NUMPY OPERATIONS ARE MUCH FASTER THAN LISTS

In [15]:
l1 = [ 1,2,3]
l2 = [5,6,7]
tuple(zip(l1,l2))

((1, 5), (2, 6), (3, 7))

In [21]:
import time 
size = 1000
l1  = list(range(size))
l2 = list(range(size))
start_time = time.time()
l3 = [x+y for x,y in zip(l1,l2)]
end_time=time.time()
print("Python list took : " , end_time-start_time )

Python list took :  0.0001628398895263672


In [22]:
n1 = np.arange(size)
n2 = np.arange(size)
n1[:4], n2[:4]

(array([0, 1, 2, 3]), array([0, 1, 2, 3]))

In [26]:
start_time = time.time()
n3 = n1 + n2
end_time = time.time()
print("Python array  took : " , end_time-start_time )

Python array  took :  9.703636169433594e-05


# CONVENIENT USE WITH BUILT-IN FUNCTIONS

In [27]:
l1 = list(range(5))
l2 = list(range(5))
l1[:3], l2[:3]

([0, 1, 2], [0, 1, 2])

In [28]:
l1 + l2 #it will concenate or will merge the two given lists

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]

In [29]:
l3 = [x+y for x,y in zip(l1,l2) ]
l3

[0, 2, 4, 6, 8]

In [31]:
n1 = np.arange(5) #in mupy we use .arange to declare size unlike list in which we use size= and range
n2 = np.arange(5)
n1,n2

(array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]))

In [32]:
n1 * n2

array([ 0,  1,  4,  9, 16])