In [1]:
#IN THIS NOTEBOOK WE WILL GO THROUGH SLICING AND STACKING IN NUMPY 

In [2]:
import numpy as np 

In [4]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [5]:
a[0:2]

array([1, 2])

In [6]:
a[3:]

array([4, 5])

In [7]:
a[-1] #it prints last element

np.int64(5)

In [8]:
a[-2:]#it prints digit from last ..like last two elements

array([4, 5])

In [10]:
b = np.array([ 
       [1,2,3],
       [4,5,6],
       [7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
b[1,2] #returns the element with is present at that position 

np.int64(6)

In [12]:
b[-1] #it prints the last row

array([7, 8, 9])

In [13]:
b[-1,0:2] #it prints last row and specifically first 2 elements

array([7, 8])

In [14]:
# Customer ID, Name
c = np.array([
    [101, 'Mira'],
    [102, 'Abdul'],
    [103, 'Andrea']
])
# Customer Id, Purchase Amount, Purchase Date
d = np.array([
    [101, 250.50, '2023-08-01'],
    [102, 150.00, '2023-08-02'],
    [103, 300.75, '2023-08-01']
])

In [15]:
np.hstack((c,d)) #we are combining these 2 array with the help of hstack which is horizontally 

array([['101', 'Mira', '101', '250.5', '2023-08-01'],
       ['102', 'Abdul', '102', '150.0', '2023-08-02'],
       ['103', 'Andrea', '103', '300.75', '2023-08-01']], dtype='<U32')

In [16]:
c

array([['101', 'Mira'],
       ['102', 'Abdul'],
       ['103', 'Andrea']], dtype='<U21')

In [17]:
e = np.array([
    [104, 'Venkat'],
    [105, 'John'],
    [106, 'Kathy'],
])

In [18]:
np.vstack((c,e)) #we are combining these 2 array with the help of vstack which is vertically 

array([['101', 'Mira'],
       ['102', 'Abdul'],
       ['103', 'Andrea'],
       ['104', 'Venkat'],
       ['105', 'John'],
       ['106', 'Kathy']], dtype='<U21')

In [19]:
transactions = np.array([
    [101, 'Mohan', 250.50, '2023-08-01'],
    [102, 'Bob', 150.00, '2023-08-02'],
    [103, 'Fatima', 300.75, '2023-08-01'],
    [104, 'David', 400.20, '2023-08-03'],
    [105, 'Aryan', 330.1, '2023-08-04'],
])

np.hsplit(transactions, [3]) #it will split the things horizontally from 3rd column 

[array([['101', 'Mohan', '250.5'],
        ['102', 'Bob', '150.0'],
        ['103', 'Fatima', '300.75'],
        ['104', 'David', '400.2'],
        ['105', 'Aryan', '330.1']], dtype='<U32'),
 array([['2023-08-01'],
        ['2023-08-02'],
        ['2023-08-01'],
        ['2023-08-03'],
        ['2023-08-04']], dtype='<U32')]

In [20]:
np.vsplit(transactions, [4]) #it will split the things vertically  from 4rd row

[array([['101', 'Mohan', '250.5', '2023-08-01'],
        ['102', 'Bob', '150.0', '2023-08-02'],
        ['103', 'Fatima', '300.75', '2023-08-01'],
        ['104', 'David', '400.2', '2023-08-03']], dtype='<U32'),
 array([['105', 'Aryan', '330.1', '2023-08-04']], dtype='<U32')]

In [21]:
monthly_sales = np.array([30, 33, 35, 28, 42])

result = monthly_sales < 32
result #it will reply with true or false 

array([ True, False, False,  True, False])

In [22]:
monthly_sales[result] #this will give the results which satisfy the condition 

array([30, 28])